[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
script = 'script'
solc_version = '0.8.19'
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
localhost = "http://localhost:8545"

[etherscan]
# You can get an API key at https://etherscan.io/apis
etherscan_api_key = "${ETHERSCAN_API_KEY}"